version: 3

tasks:
  install:
    desc: Install dependencies for both Go and Vue, and migrate database.
    cmds:
      - task: install-go
      - task: install-vue
      - |
        if command -v docker &> /dev/null; then
          echo "Using docker to create containers..."
          docker compose up -d
        elif command -v podman &> /dev/null; then
          echo "Using podman to create containers..."
          podman compose up -d
        else
          echo "No docker or podman found. Please manually edit Taskfile to support your container engine."
          return 1
        fi
      - go run ./cmd/migrate
      - go run ./cmd/miniosetup
      - go run ./cmd/redissetup
    silent: true

  install-go:
    desc: Install Go dependencies
    internal: true
    cmds:
      - go get ./...
    silent: true

  install-vue:
    desc: Install Vue dependencies
    internal: true
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm install
    silent: true

  check:
    desc: Perform static analysis for both Go and Vue.
    cmds:
      - task: check-go
      - task: check-vue

  check-go:
    desc: Perform Go static analysis
    internal: true
    cmds:
      - go fmt ./...
      - go vet ./...
    silent: true

  check-vue:
    desc: Perform Vue static analysis
    internal: true
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm -s format
      - pnpm -s lint:eslint
      - pnpm -s type-check
    silent: true

  go:
    desc: Start Go server
    cmds:
      - go run ./cmd/api
    interactive: true
    silent: true
    ignore_error: true

  vue:
    desc: Start Vue server
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm dev
    interactive: true
    silent: true
    ignore_error: true
