version: 3

vars:
  CONTAINER_ENGINE:
    sh: |
      if command -v docker &> /dev/null; then
        echo "docker"
      elif command -v podman &> /dev/null; then
        echo "podman"
      else
        echo "No docker or podman found. Please edit Taskfile manually to support your container engine." 1>&2
        exit 1
      fi
  CONTAINER_UP_TIMEOUT: 5

tasks:
  install:
    desc: Install dependencies for both Go and Web, and setup containers.
    cmds:
      - task: install-go
      - task: install-web

  up:
    desc: Setup containers.
    cmds:
      - task: start-podman
      - "{{.CONTAINER_ENGINE}} compose up -d"
      - task: sleep-windows:{{.CONTAINER_UP_TIMEOUT}}
      - task: sleep-posix:{{.CONTAINER_UP_TIMEOUT}}
      - go run ./cmd/migrate
      - go run ./cmd/miniosetup
      - go run ./cmd/redissetup
    silent: true

  down:
    desc: Teardown containers.
    cmds:
      - "{{.CONTAINER_ENGINE}} compose down -v"
    silent: true

  check:
    desc: Perform static analysis for both Go and Web.
    cmds:
      - task: check-go
      - task: check-web

  go:
    desc: Start Go server
    cmds:
      - go run ./cmd/api
    interactive: true
    silent: true
    ignore_error: true

  web:
    desc: Start Web server
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm dev
    interactive: true
    silent: true
    ignore_error: true

  install-go:
    desc: Install Go dependencies
    internal: true
    cmds:
      - go get ./...
    silent: true

  install-web:
    desc: Install Web dependencies
    internal: true
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm install
    silent: true

  check-go:
    desc: Perform Go static analysis
    internal: true
    cmds:
      - go fmt ./...
      - go vet ./...
    silent: true

  check-web:
    desc: Perform Web static analysis
    internal: true
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm -s format
      - pnpm -s lint
      - pnpm -s typecheck
    silent: true

  sleep-windows:*:
    desc: Sleep several seconds (Windows only)
    internal: true
    platforms:
      - windows
    cmds:
      - powershell -Command "Start-Sleep -Seconds {{index .MATCH 0}}"
    silent: true

  sleep-posix:*:
    desc: Sleep several seconds (POSIX platforms only)
    internal: true
    platforms:
      - linux
      - darwin
    cmds:
      - sleep {{index .MATCH 0}}
    silent: true

  start-podman:
    desc: Start Podman engine because itself does not automatically start.
    internal: true
    cmd: |
      if [[ "{{.CONTAINER_ENGINE}}" != "podman" ]]; then
        exit 0
      fi
      machinestate="$(podman machine info)"
      machinestate=${machinestate##*machinestate:}
      machinestate=${machinestate%%numberofmachines:*}
      if [[ "$machinestate" =~ Running ]]; then
        exit 0
      fi
      podman machine start
    silent: true
