package workflows

import (
	"context"
	"fmt"
	"io"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

type SkillWorkflow struct {
	workflow adk.Agent
}

func NewSkillWorkflow(chatModel model.ToolCallingChatModel) (*SkillWorkflow, error) {
	ctx := context.Background()

	overviewAgent, err := adk.NewChatModelAgent(ctx, &adk.ChatModelAgentConfig{
		Name:        "overview_agent",
		Description: "Generates SKILL.md from source code",
		Instruction: overviewSystemPrompt,
		Model:       chatModel,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create overview agent: %w", err)
	}

	apiRetrievalAgent, err := adk.NewChatModelAgent(ctx, &adk.ChatModelAgentConfig{
		Name:        "api_retrieval_agent",
		Description: "Generates API reference documentation",
		Instruction: apiRetrievalSystemPrompt,
		Model:       chatModel,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create api retrieval agent: %w", err)
	}

	workflow, err := adk.NewSequentialAgent(ctx, &adk.SequentialAgentConfig{
		Name:        "skill_generation_workflow",
		Description: "Two-stage skill generation: Overview -> API References",
		SubAgents:   []adk.Agent{overviewAgent, apiRetrievalAgent},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create sequential workflow: %w", err)
	}

	return &SkillWorkflow{
		workflow: workflow,
	}, nil
}

type WorkflowResult struct {
	Overview   string
	References []ReferenceDoc
}

type ReferenceDoc struct {
	Filename string
	Content  string
}

func (w *SkillWorkflow) Run(ctx context.Context, codeContext string) (*WorkflowResult, error) {
	runner := adk.NewRunner(ctx, adk.RunnerConfig{
		Agent:           w.workflow,
		EnableStreaming: true,
	})

	userMsg := fmt.Sprintf("Analyze the following source code and generate both SKILL.md and reference documentation:\n\n%s", codeContext)
	userMsgObj := schema.UserMessage(userMsg)
	events := runner.Run(ctx, []adk.Message{userMsgObj})

	var overviewContent, apiContent string

	for event, ok := events.Next(); ok; event, ok = events.Next() {
		if event.Output != nil && event.Output.MessageOutput != nil {
			if stream := event.Output.MessageOutput.MessageStream; stream != nil {
				for {
					chunk, err := stream.Recv()
					if err != nil {
						if err == io.EOF {
							break
						}
						return nil, err
					}

					content := chunk.Content

					if len(overviewContent) < 500 && (len(apiContent) < 100 || content[len(content)-50:] == "api.md" || content[len(content)-50:] == "reference") {
						overviewContent += content
					} else {
						apiContent += content
					}
				}
			}
		}
	}

	result := &WorkflowResult{
		Overview: overviewContent,
		References: []ReferenceDoc{
			{Filename: "api.md", Content: apiContent},
		},
	}

	return result, nil
}

const overviewSystemPrompt = `You are an expert code analyst. Your task is to analyze the provided source code and generate a standardized SKILL.md file.

The SKILL.md should include:
1. **Capability Overview**: What this codebase does
2. **Input/Output Specifications**: How to use this skill
3. **Core Features**: Main functionality
4. **Usage Examples**: Code snippets showing how to use
5. **Limitations**: Known constraints

Output the SKILL.md content clearly.`

const apiRetrievalSystemPrompt = `Based on the SKILL.md generated by the previous agent and the source code, generate detailed reference documentation.

The output should include:
1. **API Reference**: Function signatures, parameters, return types
2. **Type Definitions**: Data structures used
3. **Code Examples**: Usage patterns

Output clean Markdown for the reference documentation.`
