package workflows

import (
	"context"
	"fmt"

	"github.com/cloudwego/eino/adk"
	"github.com/cloudwego/eino/components/model"
	"github.com/cloudwego/eino/schema"
)

type SkillWorkflow struct {
	workflow          adk.Agent
	overviewAgent     adk.Agent
	apiRetrievalAgent adk.Agent
	summaryAgent      adk.Agent
}

func NewSkillWorkflow(chatModel model.ToolCallingChatModel) (*SkillWorkflow, error) {
	ctx := context.Background()

	overviewAgent, err := adk.NewChatModelAgent(ctx, &adk.ChatModelAgentConfig{
		Name:        "overview_agent",
		Description: "Generates SKILL.md from source code",
		Instruction: overviewSystemPrompt,
		Model:       chatModel,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create overview agent: %w", err)
	}

	apiRetrievalAgent, err := adk.NewChatModelAgent(ctx, &adk.ChatModelAgentConfig{
		Name:        "api_retrieval_agent",
		Description: "Generates API reference documentation",
		Instruction: apiRetrievalSystemPrompt,
		Model:       chatModel,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create api retrieval agent: %w", err)
	}

	summaryAgent, err := adk.NewChatModelAgent(ctx, &adk.ChatModelAgentConfig{
		Name:        "summary_agent",
		Description: "Generates a short summary from SKILL.md",
		Instruction: summarySystemPrompt,
		Model:       chatModel,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create summary agent: %w", err)
	}

	workflow, err := adk.NewSequentialAgent(ctx, &adk.SequentialAgentConfig{
		Name:        "skill_generation_workflow",
		Description: "Two-stage skill generation: Overview -> API References",
		SubAgents:   []adk.Agent{overviewAgent, apiRetrievalAgent},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create sequential workflow: %w", err)
	}

	return &SkillWorkflow{
		workflow:          workflow,
		overviewAgent:     overviewAgent,
		apiRetrievalAgent: apiRetrievalAgent,
		summaryAgent:      summaryAgent,
	}, nil
}

type WorkflowResult struct {
	Overview   string
	Summary    string
	References []ReferenceDoc
}

type ReferenceDoc struct {
	Filename string
	Content  string
}

func (w *SkillWorkflow) Run(ctx context.Context, codeContext string) (*WorkflowResult, error) {
	overviewRunner := adk.NewRunner(ctx, adk.RunnerConfig{
		Agent:           w.overviewAgent,
		EnableStreaming: false,
	})

	overviewMsg := fmt.Sprintf("Analyze the following source code and generate SKILL.md:\n\n%s", codeContext)
	overviewEvents := overviewRunner.Run(ctx, []adk.Message{schema.UserMessage(overviewMsg)})

	var overviewContent string
	for event, ok := overviewEvents.Next(); ok; event, ok = overviewEvents.Next() {
		if event.Output != nil && event.Output.MessageOutput != nil {
			msg := event.Output.MessageOutput.Message
			if msg != nil {
				overviewContent = msg.Content
			}
		}
	}

	summaryRunner := adk.NewRunner(ctx, adk.RunnerConfig{
		Agent:           w.summaryAgent,
		EnableStreaming: false,
	})

	summaryMsg := fmt.Sprintf("Generate a short summary (1-2 sentences, max 200 characters) for this SKILL.md:\n\n%s", overviewContent)
	summaryEvents := summaryRunner.Run(ctx, []adk.Message{schema.UserMessage(summaryMsg)})

	var summaryContent string
	for event, ok := summaryEvents.Next(); ok; event, ok = summaryEvents.Next() {
		if event.Output != nil && event.Output.MessageOutput != nil {
			msg := event.Output.MessageOutput.Message
			if msg != nil {
				summaryContent = msg.Content
			}
		}
	}

	apiRunner := adk.NewRunner(ctx, adk.RunnerConfig{
		Agent:           w.apiRetrievalAgent,
		EnableStreaming: false,
	})

	apiMsg := fmt.Sprintf("Based on the following SKILL.md and source code, generate API reference documentation:\n\nSKILL.md:\n%s\n\nSource Code:\n%s", overviewContent, codeContext)
	apiEvents := apiRunner.Run(ctx, []adk.Message{schema.UserMessage(apiMsg)})

	var apiContent string
	for event, ok := apiEvents.Next(); ok; event, ok = apiEvents.Next() {
		if event.Output != nil && event.Output.MessageOutput != nil {
			msg := event.Output.MessageOutput.Message
			if msg != nil {
				apiContent = msg.Content
			}
		}
	}

	result := &WorkflowResult{
		Overview: overviewContent,
		Summary:  summaryContent,
		References: []ReferenceDoc{
			{Filename: "api.md", Content: apiContent},
		},
	}

	return result, nil
}

const overviewSystemPrompt = `You are an expert code analyst. Your task is to analyze the provided source code and generate a standardized SKILL.md file.

The SKILL.md should include:
1. **Capability Overview**: What this codebase does
2. **Input/Output Specifications**: How to use this skill
3. **Core Features**: Main functionality
4. **Usage Examples**: Code snippets showing how to use
5. **Limitations**: Known constraints

Output the SKILL.md content clearly.`

const apiRetrievalSystemPrompt = `Based on the SKILL.md generated by the previous agent and the source code, generate detailed reference documentation.

The output should include:
1. **API Reference**: Function signatures, parameters, return types
2. **Type Definitions**: Data structures used
3. **Code Examples**: Usage patterns

Output clean Markdown for the reference documentation.`

const summarySystemPrompt = `You are a concise summarizer. Given the following SKILL.md content, generate a very short summary (1-2 sentences, maximum 200 characters) that describes what this skill does.

The summary should:
- Capture the core capability
- Be plain text, not markdown
- Be suitable for display in a card or list view

Keep it brief and informative.`
